//
//  AppPreferences.swift
//  ClipPanel
//
//  Preferences only. Clipboard content never goes near UserDefaults, or any other file, unless it is
//  pinned and encrypted (DESIGN 4.2, guarantee 2). Everything here is a setting or a flag, and the
//  exclusion list is bundle identifiers rather than anything the user copied.
//

import Foundation

nonisolated enum AppPreferences {
    private enum Key {
        static let onboardingCompleted = "hasCompletedOnboarding"
        static let historyLimit = "historyLimit"
        static let maxItemMegabytes = "maxItemMegabytes"
        static let skipTransient = "skipTransientAndAutoGenerated"
        static let excludedBundleIDs = "excludedBundleIDs"
        static let clearOnScreenLock = "clearOnScreenLock"
        static let showSourceAppCaptions = "showSourceAppCaptions"
        static let guardedLifetime = "guardedLifetimeSeconds"
        static let strictSecretMode = "strictSecretMode"
        static let clearAfterGuardedPaste = "clearClipboardAfterPastingGuarded"
        static let historyLifetime = "historyLifetimeSeconds"
        static let hotKeyKeyCode = "hotKeyKeyCode"
        static let hotKeyModifiers = "hotKeyModifiers"
        static let hotKeyLabel = "hotKeyLabel"
    }

    /// Bounds from DESIGN 2 and 8, enforced here so a hand-edited plist cannot produce a nonsense
    /// history size or a cap that swallows the machine's memory.
    static let historyLimitRange = 10...100
    static let itemMegabyteRange = 1...32

    private static var defaults: UserDefaults { .standard }

    static var hasCompletedOnboarding: Bool {
        get { defaults.bool(forKey: Key.onboardingCompleted) }
        set { defaults.set(newValue, forKey: Key.onboardingCompleted) }
    }

    static var clearOnScreenLock: Bool {
        get { defaults.object(forKey: Key.clearOnScreenLock) as? Bool ?? false }
        set { defaults.set(newValue, forKey: Key.clearOnScreenLock) }
    }

    static var showSourceAppCaptions: Bool {
        get { defaults.object(forKey: Key.showSourceAppCaptions) as? Bool ?? true }
        set { defaults.set(newValue, forKey: Key.showSourceAppCaptions) }
    }

    /// Reads the stored capture settings, falling back to the defaults for anything unset.
    static func loadCaptureSettings() -> CaptureSettings {
        var settings = CaptureSettings()

        if let limit = defaults.object(forKey: Key.historyLimit) as? Int {
            settings.historyLimit = limit.clamped(to: historyLimitRange)
        }
        if let megabytes = defaults.object(forKey: Key.maxItemMegabytes) as? Int {
            settings.maxItemBytes = megabytes.clamped(to: itemMegabyteRange) * 1024 * 1024
        }
        if let skip = defaults.object(forKey: Key.skipTransient) as? Bool {
            settings.skipTransientAndAutoGenerated = skip
        }
        if let excluded = defaults.stringArray(forKey: Key.excludedBundleIDs) {
            settings.excludedBundleIDs = Set(excluded)
        }
        if let guarded = defaults.object(forKey: Key.guardedLifetime) as? Double {
            // Clamped to at most a day: a hand-edited plist must not quietly turn "expires soon"
            // into "kept for a year" on entries the app has promised are short-lived.
            settings.guardedLifetime = min(max(guarded, 0), 86_400)
        }
        if let strict = defaults.object(forKey: Key.strictSecretMode) as? Bool {
            settings.strictSecretMode = strict
        }
        if let clear = defaults.object(forKey: Key.clearAfterGuardedPaste) as? Bool {
            settings.clearClipboardAfterPastingGuarded = clear
        }
        if let lifetime = defaults.object(forKey: Key.historyLifetime) as? Double {
            settings.historyLifetime = max(lifetime, 0)
        }
        return settings
    }

    static func save(_ settings: CaptureSettings) {
        defaults.set(settings.historyLimit, forKey: Key.historyLimit)
        defaults.set(settings.maxItemBytes / (1024 * 1024), forKey: Key.maxItemMegabytes)
        defaults.set(settings.skipTransientAndAutoGenerated, forKey: Key.skipTransient)
        defaults.set(Array(settings.excludedBundleIDs).sorted(), forKey: Key.excludedBundleIDs)
        defaults.set(settings.guardedLifetime, forKey: Key.guardedLifetime)
        defaults.set(settings.strictSecretMode, forKey: Key.strictSecretMode)
        defaults.set(settings.clearClipboardAfterPastingGuarded, forKey: Key.clearAfterGuardedPaste)
        defaults.set(settings.historyLifetime, forKey: Key.historyLifetime)
    }

    static func loadShortcut() -> GlobalShortcut {
        guard let keyCode = defaults.object(forKey: Key.hotKeyKeyCode) as? Int,
              let modifiers = defaults.object(forKey: Key.hotKeyModifiers) as? Int,
              let label = defaults.string(forKey: Key.hotKeyLabel),
              !label.isEmpty
        else {
            return .panelDefault
        }
        return GlobalShortcut(
            keyCode: UInt32(keyCode),
            carbonModifiers: UInt32(modifiers),
            keyLabel: label
        )
    }

    static func save(_ shortcut: GlobalShortcut) {
        defaults.set(Int(shortcut.keyCode), forKey: Key.hotKeyKeyCode)
        defaults.set(Int(shortcut.carbonModifiers), forKey: Key.hotKeyModifiers)
        defaults.set(shortcut.keyLabel, forKey: Key.hotKeyLabel)
    }

    static func resetShortcut() {
        defaults.removeObject(forKey: Key.hotKeyKeyCode)
        defaults.removeObject(forKey: Key.hotKeyModifiers)
        defaults.removeObject(forKey: Key.hotKeyLabel)
    }
}

nonisolated extension Int {
    /// Spelled Swift.min and Swift.max because inside an Int extension the bare names resolve to
    /// Int.min and Int.max.
    func clamped(to range: ClosedRange<Int>) -> Int {
        Swift.min(Swift.max(self, range.lowerBound), range.upperBound)
    }
}
