//
//  CaptureRules.swift
//  ClipPanel
//
//  The skip rules from DESIGN 7, as pure functions so every one of them is unit testable.
//
//  Split into two phases on purpose. Phase one decides from type identifiers alone, so a
//  concealed, excluded, or paused copy is rejected WITHOUT its payload ever being read. That
//  matters twice over: it is the difference between "we did not keep the password" and "we
//  never looked at it", and it keeps payload reads to one per clipboard change, which is what
//  the macOS 26 pasteboard privacy alert counts (DESIGN 6.1).
//

import Foundation

nonisolated enum CaptureRules {
    enum SkipReason: String, Sendable, Equatable {
        case ownPaste
        case concealed
        case transientOrAutoGenerated
        case excludedApp
        case paused
        case tooLarge
        case nothingUsable
        /// The pasteboard changed while its payload was being read; the mixed capture was discarded.
        case changedMidRead
    }

    enum PreReadDecision: Sendable, Equatable {
        case readPayload
        case skip(SkipReason)
    }

    enum PostReadDecision: Sendable, Equatable {
        case record
        case skip(SkipReason)
    }

    /// Order follows DESIGN 7 so the reported reason is the most specific one that applies.
    static func decideBeforeReading(
        types: Set<String>,
        sourceBundleID: String?,
        changeCount: Int,
        ownPasteChangeCount: Int?,
        settings: CaptureSettings
    ) -> PreReadDecision {
        if let ownPasteChangeCount, changeCount == ownPasteChangeCount {
            return .skip(.ownPaste)
        }
        if types.contains(PasteboardTypes.concealed) {
            return .skip(.concealed)
        }
        if settings.skipTransientAndAutoGenerated,
           types.contains(PasteboardTypes.transient) || types.contains(PasteboardTypes.autoGenerated) {
            return .skip(.transientOrAutoGenerated)
        }
        if let sourceBundleID, settings.excludedBundleIDs.contains(sourceBundleID) {
            return .skip(.excludedApp)
        }
        if settings.isPaused {
            return .skip(.paused)
        }
        if types.isDisjoint(with: PasteboardTypes.supported) {
            return .skip(.nothingUsable)
        }
        return .readPayload
    }

    /// Size is only knowable after reading, so it lands here along with "the payload turned
    /// out to be unusable" (empty data, an image that would not decode, and so on).
    static func decideAfterReading(
        byteSize: Int,
        exceededReadLimit: Bool,
        producedUsableItem: Bool,
        settings: CaptureSettings
    ) -> PostReadDecision {
        if exceededReadLimit || byteSize > settings.maxItemBytes {
            return .skip(.tooLarge)
        }
        guard producedUsableItem else {
            return .skip(.nothingUsable)
        }
        return .record
    }
}
