//
//  CaptureSettings.swift
//  ClipPanel
//

import Foundation

/// Everything that changes what gets captured. Held in memory for M2; M6 binds it to
/// UserDefaults, which stores preferences only and never clipboard content.
nonisolated struct CaptureSettings: Sendable, Equatable {
    /// Windows keeps 25. Configurable 10 to 100 in M6.
    var historyLimit: Int = 25
    /// Windows caps an item at roughly 4 MB. Oversized copies are not recorded at all; the
    /// system clipboard itself is untouched, so the user can still paste normally.
    var maxItemBytes: Int = 4 * 1024 * 1024
    /// Images get their own, far larger cap: a Retina screenshot's PNG routinely exceeds the
    /// text cap, and "screenshots silently vanish" is a bug report, not a policy. The total
    /// memory budget below is what actually protects the machine.
    var maxImageItemBytes: Int = 64 * 1024 * 1024
    /// Ceiling on the summed size of all unpinned entries. When new captures push past it, the
    /// oldest unpinned entries are evicted, the same order the count limit uses. This is the
    /// limit that keeps twenty-five large screenshots from quietly costing a gigabyte of RAM.
    var maxTotalBytes: Int = 256 * 1024 * 1024

    /// The per-item cap that applies to a capture with these declared types.
    func effectiveCap(forTypes types: Set<String>) -> Int {
        types.isDisjoint(with: PasteboardTypes.imageTypes) ? maxItemBytes : maxImageItemBytes
    }
    /// Skip copies marked transient or auto generated by the source app.
    var skipTransientAndAutoGenerated: Bool = true
    var excludedBundleIDs: Set<String> = ExclusionList.suggestedDefaults
    var isPaused: Bool = false

    // MARK: Secret Guard (REVIEW.md part 2)

    /// How long a guarded (probably-secret) entry lives before it expires from history, unless
    /// pinned. The password pasted four times this morning should not still be sitting in the
    /// panel this afternoon.
    var guardedLifetime: TimeInterval = 300
    /// Strict mode: detected secrets are not recorded at all, same as concealed ones. Off by
    /// default because a false positive then becomes invisible data loss.
    var strictSecretMode: Bool = false
    /// After pasting a guarded entry, clear the system clipboard a minute later if it still holds
    /// what we wrote, the way password managers clear their own copies.
    var clearClipboardAfterPastingGuarded: Bool = true
    /// Expire ANY unpinned entry older than this. Zero means off. The agent runs for weeks, so
    /// "history until quit" quietly becomes "history forever" without it.
    var historyLifetime: TimeInterval = 0
}

nonisolated enum ExclusionList {
    /// Apps whose copies are secrets by definition.
    ///
    /// Most of these already mark copies with ConcealedType, which is honoured regardless of
    /// this list and cannot be switched off. This is the belt to that pair of braces, for
    /// versions and forks that forget the marker.
    ///
    /// Terminals are deliberately absent (DESIGN 12, open question 2): people copy from them
    /// constantly, so they ship as a suggested toggle in M6 rather than a silent default.
    static let suggestedDefaults: Set<String> = [
        "com.1password.1password",
        "com.1password.browser-support",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.Dashlane",
    ]
}
