//
//  CaptureSettings.swift
//  ClipPanel
//

import Foundation

/// Everything that changes what gets captured. Held in memory for M2; M6 binds it to
/// UserDefaults, which stores preferences only and never clipboard content.
nonisolated struct CaptureSettings: Sendable, Equatable {
    /// Windows keeps 25. Configurable 10 to 100 in M6.
    var historyLimit: Int = 25
    /// Windows caps an item at roughly 4 MB. Oversized copies are not recorded at all; the
    /// system clipboard itself is untouched, so the user can still paste normally.
    var maxItemBytes: Int = 4 * 1024 * 1024
    /// Skip copies marked transient or auto generated by the source app.
    var skipTransientAndAutoGenerated: Bool = true
    var excludedBundleIDs: Set<String> = ExclusionList.suggestedDefaults
    var isPaused: Bool = false
}

nonisolated enum ExclusionList {
    /// Apps whose copies are secrets by definition.
    ///
    /// Most of these already mark copies with ConcealedType, which is honoured regardless of
    /// this list and cannot be switched off. This is the belt to that pair of braces, for
    /// versions and forks that forget the marker.
    ///
    /// Terminals are deliberately absent (DESIGN 12, open question 2): people copy from them
    /// constantly, so they ship as a suggested toggle in M6 rather than a silent default.
    static let suggestedDefaults: Set<String> = [
        "com.1password.1password",
        "com.1password.browser-support",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.Dashlane",
    ]
}
