//
//  PasteboardTypes.swift
//  ClipPanel
//

import Foundation

/// Pasteboard type identifiers we care about, as raw strings so the pure logic and its tests
/// never need AppKit.
nonisolated enum PasteboardTypes {
    // MARK: Marker types (nspasteboard.org convention)
    //
    // These are a community convention rather than SDK constants, which is exactly why they
    // are spelled out here. Password managers set ConcealedType on copies that must not be
    // retained, and honouring it is the single most effective secret-capture defence we have.

    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    // MARK: Content types

    static let plainText = "public.utf8-plain-text"
    static let rtf = "public.rtf"
    static let html = "public.html"
    static let png = "public.png"
    static let tiff = "public.tiff"
    static let fileURL = "public.file-url"

    /// A copy is only worth recording if it carries at least one of these.
    static let supported: Set<String> = [plainText, rtf, html, png, tiff, fileURL]

    static let imageTypes: Set<String> = [png, tiff]
}
