//
//  AppPreferencesTests.swift
//  ClipPanelTests
//

import Foundation
import Testing

@testable import ClipPanel

/// These exercise the clamping and round-tripping logic, against the isolated test suite domain
/// (AppPreferences.defaults under test), never the user's real preferences. Each test still
/// restores what it changed so tests stay independent of each other.
@Suite("App preferences", .serialized)
@MainActor
struct AppPreferencesTests {
    private func withCleanDefaults(_ body: () -> Void) {
        let keys = [
            "historyLimit", "maxItemMegabytes", "skipTransientAndAutoGenerated",
            "excludedBundleIDs", "hotKeyKeyCode", "hotKeyModifiers", "hotKeyLabel",
        ]
        let saved = keys.map { ($0, AppPreferences.defaults.object(forKey: $0)) }
        keys.forEach { AppPreferences.defaults.removeObject(forKey: $0) }

        body()

        for (key, value) in saved {
            if let value {
                AppPreferences.defaults.set(value, forKey: key)
            } else {
                AppPreferences.defaults.removeObject(forKey: key)
            }
        }
    }

    @Test("With nothing stored, the documented defaults apply")
    func defaultsWhenUnset() {
        withCleanDefaults {
            let settings = AppPreferences.loadCaptureSettings()
            #expect(settings.historyLimit == 25)
            #expect(settings.maxItemBytes == 4 * 1024 * 1024)
            #expect(settings.skipTransientAndAutoGenerated)
            #expect(settings.excludedBundleIDs == ExclusionList.suggestedDefaults)
        }
    }

    @Test("Capture settings round trip")
    func captureSettingsRoundTrip() {
        withCleanDefaults {
            var settings = CaptureSettings()
            settings.historyLimit = 50
            settings.maxItemBytes = 8 * 1024 * 1024
            settings.skipTransientAndAutoGenerated = false
            settings.excludedBundleIDs = ["com.example.one", "com.example.two"]

            AppPreferences.save(settings)
            let loaded = AppPreferences.loadCaptureSettings()

            #expect(loaded.historyLimit == 50)
            #expect(loaded.maxItemBytes == 8 * 1024 * 1024)
            #expect(loaded.skipTransientAndAutoGenerated == false)
            #expect(loaded.excludedBundleIDs == ["com.example.one", "com.example.two"])
        }
    }

    @Test("A hand-edited history limit is clamped to the supported range", arguments: [
        (1, 10), (9, 10), (10, 10), (100, 100), (5000, 100),
    ])
    func historyLimitIsClamped(stored: Int, expected: Int) {
        withCleanDefaults {
            AppPreferences.defaults.set(stored, forKey: "historyLimit")
            #expect(AppPreferences.loadCaptureSettings().historyLimit == expected)
        }
    }

    @Test("A hand-edited size cap is clamped to the supported range", arguments: [
        (0, 1), (1, 1), (32, 32), (4096, 32),
    ])
    func sizeCapIsClamped(storedMegabytes: Int, expectedMegabytes: Int) {
        withCleanDefaults {
            AppPreferences.defaults.set(storedMegabytes, forKey: "maxItemMegabytes")
            #expect(AppPreferences.loadCaptureSettings().maxItemBytes
                    == expectedMegabytes * 1024 * 1024)
        }
    }

    @Test("The shortcut round trips, and falls back to the default when incomplete")
    func shortcutRoundTrip() {
        withCleanDefaults {
            #expect(AppPreferences.loadShortcut() == .panelDefault)

            let custom = GlobalShortcut(keyCode: 8, carbonModifiers: 256, keyLabel: "C")
            AppPreferences.save(custom)
            #expect(AppPreferences.loadShortcut() == custom)

            // A half-written record must not produce a broken shortcut.
            AppPreferences.defaults.removeObject(forKey: "hotKeyLabel")
            #expect(AppPreferences.loadShortcut() == .panelDefault)

            AppPreferences.resetShortcut()
            #expect(AppPreferences.loadShortcut() == .panelDefault)
        }
    }

    @Test("Lowering the history limit takes effect immediately")
    func loweringLimitEvictsNow() {
        let store = HistoryStore()
        let base = Date(timeIntervalSince1970: 1_000_000)
        for index in 0..<10 {
            store.record(textItem("entry \(index)", at: base.addingTimeInterval(Double(index))))
        }
        #expect(store.items.count == 10)

        store.settings.historyLimit = 3
        store.enforceLimit()

        #expect(store.items.count == 3)
        #expect(store.items.first?.preview == .text("entry 9"))
    }
}
