//
//  CaptureRulesTests.swift
//  ClipPanelTests
//

import Foundation
import Testing

@testable import ClipPanel

@Suite("Capture rules, before reading payloads")
struct CaptureRulesPreReadTests {
    private let settings = CaptureSettings()

    @Test("Ordinary text copy is accepted")
    func plainTextIsRead() {
        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText],
            sourceBundleID: "com.apple.TextEdit",
            changeCount: 4,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .readPayload)
    }

    @Test("Our own paste is not captured back")
    func ownPasteIsSkipped() {
        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText],
            sourceBundleID: "com.apple.TextEdit",
            changeCount: 9,
            ownPasteChangeCount: 9,
            settings: settings
        )
        #expect(decision == .skip(.ownPaste))
    }

    @Test("Concealed copies are never captured")
    func concealedIsSkipped() {
        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText, PasteboardTypes.concealed],
            sourceBundleID: "com.example.somepasswordmanager",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .skip(.concealed))
    }

    @Test("Concealed cannot be switched off by settings")
    func concealedIgnoresSettings() {
        var permissive = CaptureSettings()
        permissive.skipTransientAndAutoGenerated = false
        permissive.excludedBundleIDs = []

        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText, PasteboardTypes.concealed],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: permissive
        )
        #expect(decision == .skip(.concealed))
    }

    @Test("Transient and auto generated copies are skipped by default", arguments: [
        PasteboardTypes.transient,
        PasteboardTypes.autoGenerated,
    ])
    func transientSkipped(marker: String) {
        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText, marker],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .skip(.transientOrAutoGenerated))
    }

    @Test("Transient copies are kept when the user turns that off")
    func transientAllowedWhenDisabled() {
        var permissive = CaptureSettings()
        permissive.skipTransientAndAutoGenerated = false

        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText, PasteboardTypes.transient],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: permissive
        )
        #expect(decision == .readPayload)
    }

    @Test("Copies from excluded apps are skipped")
    func excludedAppSkipped() {
        let excluded = ExclusionList.suggestedDefaults.first!
        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText],
            sourceBundleID: excluded,
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .skip(.excludedApp))
    }

    @Test("Nothing is captured while paused")
    func pausedSkipped() {
        var paused = CaptureSettings()
        paused.isPaused = true

        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: paused
        )
        #expect(decision == .skip(.paused))
    }

    @Test("Copies with no type we understand are skipped")
    func unsupportedTypesSkipped() {
        let decision = CaptureRules.decideBeforeReading(
            types: ["com.example.proprietary"],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .skip(.nothingUsable))
    }

    @Test("Concealed takes precedence over the excluded app reason")
    func concealedBeatsExcluded() {
        var settings = CaptureSettings()
        settings.excludedBundleIDs = ["com.example.app"]

        let decision = CaptureRules.decideBeforeReading(
            types: [PasteboardTypes.plainText, PasteboardTypes.concealed],
            sourceBundleID: "com.example.app",
            changeCount: 1,
            ownPasteChangeCount: nil,
            settings: settings
        )
        #expect(decision == .skip(.concealed))
    }
}

@Suite("Capture rules, after reading payloads")
struct CaptureRulesPostReadTests {
    private let settings = CaptureSettings()

    @Test("A normal sized item is recorded")
    func recordsNormalItem() {
        let decision = CaptureRules.decideAfterReading(
            byteSize: 1024,
            exceededReadLimit: false,
            producedUsableItem: true,
            settings: settings
        )
        #expect(decision == .record)
    }

    @Test("An item over the cap is skipped")
    func skipsOversizedItem() {
        let decision = CaptureRules.decideAfterReading(
            byteSize: settings.maxItemBytes + 1,
            exceededReadLimit: false,
            producedUsableItem: true,
            settings: settings
        )
        #expect(decision == .skip(.tooLarge))
    }

    @Test("A read abandoned for size is skipped")
    func skipsAbandonedRead() {
        let decision = CaptureRules.decideAfterReading(
            byteSize: 0,
            exceededReadLimit: true,
            producedUsableItem: false,
            settings: settings
        )
        #expect(decision == .skip(.tooLarge))
    }

    @Test("An item that yielded no preview is skipped")
    func skipsUnusableItem() {
        let decision = CaptureRules.decideAfterReading(
            byteSize: 10,
            exceededReadLimit: false,
            producedUsableItem: false,
            settings: settings
        )
        #expect(decision == .skip(.nothingUsable))
    }
}
