//
//  RepresentationPolicyTests.swift
//  ClipPanelTests
//

import Foundation
import Testing

@testable import ClipPanel

@Suite("Representation policy")
struct RepresentationPolicyTests {
    @Test("TIFF is dropped when PNG is present, so screenshots fit the cap")
    func tiffDroppedNextToPNG() {
        let kept = RepresentationPolicy.typesToStore(
            from: [PasteboardTypes.tiff, PasteboardTypes.png]
        )
        #expect(kept == [PasteboardTypes.png])
    }

    @Test("TIFF survives when it is the only image representation")
    func loneTiffSurvives() {
        let kept = RepresentationPolicy.typesToStore(
            from: [PasteboardTypes.tiff, PasteboardTypes.plainText]
        )
        #expect(kept.contains(PasteboardTypes.tiff))
    }

    @Test("Exotic private types are not read or stored")
    func exoticTypesDropped() {
        let kept = RepresentationPolicy.typesToStore(from: [
            "org.chromium.web-custom-data",
            PasteboardTypes.plainText,
            "com.apple.WebKit.custom-pasteboard-data",
            PasteboardTypes.html,
        ])
        #expect(kept == [PasteboardTypes.plainText, PasteboardTypes.html])
    }

    @Test("Marker types are never stored")
    func markersDropped() {
        let kept = RepresentationPolicy.typesToStore(from: [
            PasteboardTypes.plainText,
            PasteboardTypes.transient,
            PasteboardTypes.autoGenerated,
        ])
        #expect(kept == [PasteboardTypes.plainText])
    }

    @Test("Declaration order is preserved")
    func orderPreserved() {
        let kept = RepresentationPolicy.typesToStore(from: [
            PasteboardTypes.rtf, PasteboardTypes.plainText, PasteboardTypes.html,
        ])
        #expect(kept == [PasteboardTypes.rtf, PasteboardTypes.plainText, PasteboardTypes.html])
    }
}
